### ISSUE TITLE
[request] edit `MDItemFSCreationDate` tag example

### ISSUE THREAD

**Issue by mesqueeb** [mceachen/exiftool-vendored.js#10]
Would it be possible to add an example how to edit the macOS "file creation date" ?
This is a special tag called `MDItemFSCreationDate` which needs a special option before it can be accessed through exiftool.

From [the exiftool docs](https://sno.phy.queensu.ca/~phil/exiftool/TagNames/MacOS.html#MDItem):
> MDItem tags are extracted using the "mdls" utility. They are extracted if any "MDItem*" tag or the MacOS group is specifically requested, or by setting the MDItemTags API option to 1 or the RequestAll API option to 2 or higher.

e.g. `-tagsfromfile @ -MDItemFSCreationDate`

**Comment by mceachen** [comment]
Dude, srsly, RTFM. You've opened how many tickets now that are all "please do free work for me?"

**Comment by mceachen** [comment]
You can pass options to ExifTool via the second argument in `ExifTool.read()`. Looks like either `RequestAll=2` or `MDItemTags=1` work.

```js
exiftool.read("test/img.jpg", ["-api", "MDItemTags=2"]).then(console.dir)
```
