### ISSUE TITLE
[request] elaboration on `Timezones` documentation

### ISSUE THREAD

**Issue by mesqueeb** [mceachen/exiftool-vendored.js#11]
From your docs:
> Always Beware: Timezones
If you edit a timestamp tag, realize that the difference between the changed timestamp tag and the GPS value is used by exiftool-vendored to infer the timezone.
In other words, if you only edit the CreateDate and don't edit the GPS timestamps, your timezone will either be incorrect or missing.

Is it possible to elaborate on which `GPS timestamps` we need to edit?

The reason being: I have a bunch of scanned photos I'm adding the date taken to manually.
At first I thought of just writing the dates as mentioned: `exiftool.write("path/to/file.jpg", { AllDates: "2016-02-06T16:56:00" });`
But after reading this I got a bit scared that wouldn't be enough.

**Comment by mceachen** [comment]
You need to review your own metadata. I can't do that for you.
