### ISSUE TITLE
concerning -stay_open

### ISSUE THREAD

**Issue by mesqueeb** [mceachen/exiftool-vendored.js#13]
Dear @mceachen 

I'm really sorry to make another post, and I don't try to make you do free work for me.
In fact, if you have a paypal account or a bitcoin address, I'd be happy to tip you!!

You see, I'm having a problem understanding how to use `-stay_open`.
I read the [official documentation about -stay_open](https://sno.phy.queensu.ca/~phil/exiftool/exiftool_pod.html#stay_open-FLAG) but I'm afraid, it's really difficult to understand...

I have about 10,000 image paths that I want to edit with exiftool. I'm doing it like so:
```JavaScript
imgPaths.forEach(imgPath => {
  // get the date from a json file
  let parentFolder = imgPath.split('/')[imgPath.split('/').length-2]
  let comment = folderInfo['keywords']
  let date = folderInfo['date']+' 12:00:00.000+01:00'
  // do the exiftool write
  exiftool
  .write(imgPath, {
    'MDItemFSCreationDate': date,
    'AllDates': date,
  })
  .then(suc => success(suc)).catch(err => catchErr(err))
```
But every time it hangs around 3000 images, so I think the memory is up. It's so bad I have to restart the computer after...

Do you have any advice on how to add `-stay_open` to this? I tried it as a third argument to the write function, but it didn't work.

Feel free to delete this thread if you want. I don't want to trouble you too much...
I'm so sorry, I don't know who else to ask.

**Comment by mceachen** [comment]
> I'm so sorry, I don't know who else to ask.
https://stackoverflow.com/ is a great resource.

You aren't `await`ing on any of the write promises, so your CPUs are being overwhelmed. Review the [ExifTool constructor parameters](https://github.com/mceachen/exiftool-vendored.js/blob/master/src/ExifTool.ts#L55)
and override default values where appropriate. I suggest being very conservative just to get things to work, by setting `maxProcs` to 1, and `maxTasksPerProcess` to be 10. Good luck.

**Comment by mceachen** [comment]
To avoid other people having this same problem, I just dropped the default `maxProcs` value to a quarter of CPUs available on the system and released v4.9.1.

**Comment by mceachen** [comment]
Did the reduction in the `maxProcs` default fix your issue?

**Comment by mesqueeb** [comment]
@mceachen Just now I am revisiting my photo library and have to make additional changes to its tags.

Again, I'd like to make changes to about 20,000 photos this time, but you have indicated that with the setup that I had there is no automatic throttling applied:

```js
imgPaths.forEach(imgPath => {
  exiftool
  .write(imgPath, {
```

Do you have any advice in how to best throttle a setup like above to only make changes on eg. 1000 images at a time?

**Comment by mceachen** [comment]
Each write returns a promise that you could await, but it sounds like you
should just use exiftool directly. It has support for recursion, filtering,
and conditionals.

https://sno.phy.queensu.ca/~phil/exiftool/exiftool_pod.html#WRITING-EXAMPLES

Also, from the front page:

    If you find the need to use "find" or "awk" in conjunction with
ExifTool, then you probably haven't discovered the full power of ExifTool.
Read about the -ext, -if, -p and -tagsFromFile options in the application
documentation (https://sno.phy.queensu.ca/~phil/exiftool/exiftool_pod.html)
(This is common mistake number 3,
https://sno.phy.queensu.ca/~phil/exiftool/mistakes.html#M3)

>
