### ISSUE TITLE
Bug spawning new process with electron

### ISSUE THREAD

**Issue by Circuit8** [mceachen/exiftool-vendored.js#17]
Hi there,
First of all thanks for your work on exiftool-vendored, its a great library and a huge help to me!

So I'm using Electron and in development exiftool-vendored is working perfectly. However when I build for production and attempt to write to a file I'm getting the following errors in the console:

![screenshot](https://user-images.githubusercontent.com/6171759/36972637-c4829d0e-2067-11e8-9c3b-aa20f425499d.png)

I'm using exiftool-vendored version `4.18.1` and running on Ubuntu

Cheers

**Comment by mceachen** [comment]
There is so much flexibility and no clear standard in packaging Electron apps, and a lot of sharp bits to poke you. It took me a while to get the right combination of electron packaging (I am using [electron-builder](https://www.electron.build/), webpack config, `asar` exclusions, and `__dirname` workarounds to make everything work cross-platform. Electron isn't quite the "everything just works" solution it advertises, unfortunately.

Good luck! If you want to contribute a wiki page describing how you got your app working, the [wiki](https://github.com/mceachen/exiftool-vendored.js/wiki) should be open to your edits, and you contributions would be most welcome!
