### ISSUE TITLE
Are all the tags represented?

### ISSUE THREAD

**Issue by cjemmerson** [mceachen/exiftool-vendored.js#18]
Hi,
Im having trouble cross referencing the tags with the tag names listed on exiftool. For example I'm trying to edit fields such as 'By-Line' and 'Headline' as shown here: https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/IPTC.html#ApplicationRecord
but cant seem to find any such tags on your list? Might they be labelled under a different name or are those particular fields just not included? 
Thanks

**Comment by mceachen** [comment]
Good question! I've added an answer to this in the [FAQ](https://github.com/mceachen/exiftool-vendored.js/wiki#where-do-you-get-your-tag-entries-from). 

Do you think that solution will work, or do you think we need to hard-code some tags? I was trying to avoid that, given that those lists would fall out of sync with ExifTool's implementation (as it has monthly and sometimes weekly updates).

**Comment by mceachen** [comment]
Closing. Let's reopen if the given solution won't work for you.
