### ISSUE TITLE
Support for remote URLs

### ISSUE THREAD

**Issue by claudiopetrini** [mceachen/exiftool-vendored.js#2]
It would be really nice to be able to use a remote URLs instead of a local path so that nothing is persisted on the file system.

I'm not that into the source code, TypeScript and ExifTool to make a PR however.

**Comment by mceachen** [comment]
AFAICT, ExifTool in `-stay_open` mode only supports reads from the local filesystem, so even if we did the URL content fetching to a node `Buffer`, we'd still need to shove the contents into a tempfile. In general, reading from a local filesystem is going to be way faster than reading from the network, so the tempfile I/O is going to be negligible compared to the network latency.

If others know of alternative approaches, I'm happy to revisit this.

**Comment by claudiopetrini** [comment]
Thank you again the response.

Unfortunately my use case needs to retrieve images from a remote URL so the network latency is something that I can't avoid.

Saving data into a buffer doesn't mean necessarily to write a tempfile, the whole file could fit into memory or data could be processed as stream (which could be a really interesting solution). 
However I'm [reading](http://u88.n24.queensu.ca/exiftool/forum/index.php?topic=6845.0) that with the `-stay_open` option it's not possible to process a stream.

Again I don't know ExitTool so forgive me if there are any inaccuracies.

**Comment by mceachen** [comment]
> However I'm reading that with the -stay_open option it's not possible to process a stream.

Unfortunately, that's how I read that too.

I played around with `[mkfifo](https://en.wikipedia.org/wiki/Named_pipe)` and that *does* work, but you'd still have to make that named pipe on the host machine. 

FWIW, I'm using [tmp](https://www.npmjs.com/package/tmp) for this use case and it's working well. By streaming to a unique tempfile per URL, you can download multiple URLs concurrently. You wouldn't be able to do that with a single named pipe.

**Comment by claudiopetrini** [comment]
Thank you for the informations.

**Comment by kapouer** [comment]
exiftool actually *can* process stdin !
See https://github.com/kapouer/node-streat/blob/master/lib/streat.js#L47
i'm using it to avoid downloading huge files to get metadata about them.
It's still not perfect but it shows it's possible to do it.

**Comment by mceachen** [comment]
@kapouer how do you provide a stream to exiftool when it is launched in `-stay_open` mode?

**Comment by kapouer** [comment]
Oh ! i forgot how i did that. Apparently i cheat using a temporary file and sending commands to read partial file.

**Comment by kapouer** [comment]
This allows to get metadata without downloading the whole file.

**Comment by mceachen** [comment]
@kapouer spawning exiftool with `-stay_open True -@ -` is exactly how this library works, so it can leverage the spinup of a single exiftool instance. "stay_open" mode isn't compatible with file streams. See http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,6845.msg34376.html#msg34376
