### ISSUE TITLE
Typescript Definition of "WriteTags" does not contain "AllDates"  

### ISSUE THREAD

**Issue by nknapp** [mceachen/exiftool-vendored.js#21]
I tried to write `{ AllDates: "some iso date" }`, but appearently `WriteTags` does not contain `AllDates`. The TypeScript-compiler fails on this 

```ts
new ExifTool().write(file, { AllDates: '2017-07-27T10:28:35.000Z' })
```

**Comment by mceachen** [comment]
`Tags.ts` only includes tags actually returned from sample images and videos (the "ground truth," after I wasted a lot of time querying for tags that no one actually uses). 

I don't believe any of the [composite tags](https://sno.phy.queensu.ca/~phil/exiftool/TagNames/Shortcuts.html) are going to be there, in fact.

I'd be happy to accept a PR that defined the writable composite tags interface, and then we can add that to the `WriteTags` interface.

**Comment by nknapp** [comment]
I have started a fork for such a PR. But I have not been able to write a test-case that actually uses the "AllDates"-tag. The change would consist of changing [this line](https://github.com/mceachen/exiftool-vendored.js/blob/master/src/ExifTool.ts#L55) to

```
export type WriteTags = { [K in keyof Tags]: string | number } & { AllDates?: string | number }
```

Is that correct?

**Comment by mceachen** [comment]
I wasn't sure if you could provide a aggregate type in `keyof`--it was only a couple more minutes to just finish the patch. I'll release v4.22 in a moment.
