### ISSUE TITLE
Any way to get Node.js streams to work?

### ISSUE THREAD

**Issue by DungFu** [mceachen/exiftool-vendored.js#22]
Having to manage and deal with temporary files all over the place (not to mention the *_original files) is kind of a pain. Being able to work with node streams directly would make this much easier.

For example, exiftool.read() could take a stream. Functions like extractPreview(filepath/inputstream) could take 1 argument (file or stream) and then process the output by either having .write(newfilepath) or .stream().pipe(outputstream). The gm package has a really nice way of handling this (https://github.com/aheckmann/gm)

Is there any way to work with streams currently or is it purely a feature that is not implemented yet? And if so, are there any plans to support streams in the future?

**Comment by mceachen** [comment]
This was discussed in #2. The TL;DR: ExifTool doesn't support this use case, so we can't either. I've been using tmpfiles, myself.

https://github.com/mceachen/exiftool-vendored.js/issues/2#issuecomment-390003161
