### ISSUE TITLE
Missing rejection from `.read()`

### ISSUE THREAD

**Issue by Shuunen** [mceachen/exiftool-vendored.js#23]
Hi there :slightly_smiling_face: 

First I'd like to thanks @mceachen & contributors of this lib which is great :+1: 

Then today I experienced a weird problem, here is the context : 
- I created a script that correct exif dates of my photos
- It read with `exiftool.read(filepath) .then(tags => ...)`
- And write new date like in documentation  `exiftool.write(filepath, { AllDates: newDateStr })`

This script worked on multiple files before failing on a particular file.

The first problem here is that all my code is wrapped with catch and no error popped out, it just stops code execution after `exiftool.write` and never come into the `then` or `catch`

I managed to find the problem by using ExifTool via command line: `Error reading ThumbnailImage data`

So this is the error that should have appeared before and wasn't thrown.

Then I managed to found on the ExifTool author faq http://owl.phy.queensu.ca/~phil/exiftool/faq.html#Q20 that you can repair file exif with : 
`exiftool -all= -tagsfromfile @ -all:all -unsafe -icc_profile bad-file.jpg`

So I would suggest implementing this repair ability as a method of this lib or as an option when writing :) 

What do you think?

**Comment by mceachen** [comment]
Thanks for taking the time to write this!

Could you share your problematic image? The promise from `.read()` should have been rejected, and I'd like to add that to a new test. We can strip the image content if you're concerned at all about privacy before we commit it to the repo.

What do you think your proposed method should be called? I'm thinking something like:

```ts
/**
 * Attempt to fix metadata problems in JPEG images by deleting all metadata and rebuilding from 
 * scratch. After repairing an image you should be able to write to it without errors, but some 
 * metadata from the original image may be lost in the process.
 * 
 * This should only be applied as a last resort to images whose metadata is not readable via 
 * {@link .read()}.
 *
 * @param {string} file the path to the image
 * @param {boolean} allowMakerNoteRepair if there are problems with MakerNote tags, allow
 * ExifTool to apply heuristics to recover corrupt tags. See exiftool's `-F` flag.
 * @return {Promise<string>} when the file has been rewritten. 
 */
rewriteAllTags(file: string, allowMakerNoteRepair = false)
```

**Comment by Shuunen** [comment]
My bad, the error is displayed when writing tag :smile: 

I made this so you can clone & reproduce : https://github.com/Shuunen/issues/tree/mceachen/exiftool-vendored.js/issues/23

But if you comment the write section, no error thrown on reading

And your `rewriteAllTags` seems good to me :+1:

**Comment by mceachen** [comment]
I updated your package.json to use the v5.0.0:

### Ubuntu 18.04

``` 
$ node .
issue : start
got tags :  SourceFile, errors, ExifToolVersion, FileName, Directory, FileSize, FileModifyDate, FileAccessDate, FileInodeChangeDate, FilePermissions, FileType, FileTypeExtension, MIMEType, JFIFVersion, Comment, ExifByteOrder, Make, Model, Orientation, XResolution, YResolution, ResolutionUnit, Software, ModifyDate, YCbCrPositioning, ExposureTime, FNumber, ExposureProgram, ISO, ExifVersion, DateTimeOriginal, CreateDate, ComponentsConfiguration, ShutterSpeedValue, ApertureValue, BrightnessValue, ExposureCompensation, MaxApertureValue, MeteringMode, Flash, FocalLength, ColorSpace, ExifImageWidth, ExifImageHeight, ExposureMode, WhiteBalance, SceneCaptureType, Contrast, Saturation, Sharpness, GPSVersionID, GPSLatitudeRef, GPSLongitudeRef, GPSAltitudeRef, Padding, Compression, ThumbnailOffset, ThumbnailLength, ImageWidth, ImageHeight, EncodingProcess, BitsPerSample, ColorComponents, YCbCrSubSampling, Aperture, GPSAltitude, ImageSize, Megapixels, ShutterSpeed, ThumbnailImage, FocalLength35efl, LightValue
reading went good
writing a new date
Task.onError(): rejected { command: '-AllDates=2016-02-06T16:56:00\n-charset\nfilename=utf8\n-codedcharacterset=utf8\n/home/mrm/src/issues/problematic.jpg\n-ignoreMinorErrors\n-execute\n',
  error: Error: Error: Error reading ThumbnailImage data in IFD1 - /home/mrm/src/issues/problematic.jpg
    at Socket.<anonymous> (/home/mrm/src/issues/node_modules/batch-cluster/dist/BatchProcess.js:81:49)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onread (net.js:581:20) }
error happend : Error: Error: Error reading ThumbnailImage data in IFD1 - /home/mrm/src/issues/problematic.jpg
    at Socket.<anonymous> (/home/mrm/src/issues/node_modules/batch-cluster/dist/BatchProcess.js:81:49)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onread (net.js:581:20)
closing exiftool instance
issue : end
```

### Windows 10

```
$ node .
issue : start
got tags :  SourceFile, errors, ExifToolVersion, FileName, Directory, FileSize, FileModifyDate, FileAccessDate, FileCreateDate, FilePermissions, FileType, FileTypeExtension, MIMEType, JFIFVersion, Comment, ExifByteOrder, Make, Model, Orientation, XResolution, YResolution, ResolutionUnit, Software, ModifyDate, YCbCrPositioning, ExposureTime, FNumber, ExposureProgram, ISO, ExifVersion, DateTimeOriginal, CreateDate, ComponentsConfiguration, ShutterSpeedValue, ApertureValue, BrightnessValue, ExposureCompensation, MaxApertureValue, MeteringMode, Flash, FocalLength, ColorSpace, ExifImageWidth, ExifImageHeight, ExposureMode, WhiteBalance, SceneCaptureType, Contrast, Saturation, Sharpness, GPSVersionID, GPSLatitudeRef, GPSLongitudeRef, GPSAltitudeRef, Padding, Compression, ThumbnailOffset, ThumbnailLength, ImageWidth, ImageHeight, EncodingProcess, BitsPerSample, ColorComponents, YCbCrSubSampling, Aperture, GPSAltitude, ImageSize, Megapixels, ShutterSpeed, ThumbnailImage, FocalLength35efl, LightValue
reading went good
writing a new date
Task.onError(): rejected { command: '-AllDates=2016-02-06T16:56:00\n-charset\nfilename=utf8\n-codedcharacterset=utf8\nC:\\Users\\mrm\\src\\issues\\problematic.jpg\n-ignoreMinorErrors\n-execute\n',
  error: Error: Error: Error reading ThumbnailImage data in IFD1 - C:/Users/mrm/src/issues/problematic.jpg
    at Socket.<anonymous> (C:\Users\mrm\src\issues\node_modules\batch-cluster\dist\BatchProcess.js:81:49)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20) }
error happend : Error: Error: Error reading ThumbnailImage data in IFD1 - C:/Users/mrm/src/issues/problematic.jpg
    at Socket.<anonymous> (C:\Users\mrm\src\issues\node_modules\batch-cluster\dist\BatchProcess.js:81:49)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)
closing exiftool instance
issue : end
```

**Comment by mceachen** [comment]
So... that `error: Error: Error: Error` isn't great. Darn. I'll fix, but I don't see the your "no error, no catch" issue. I'm using node v9.11.1 on Ubuntu and v8.10.0 on windows.

**Comment by Shuunen** [comment]
I'll give you more details as soon as I get back to my windows computer :)

**Comment by Shuunen** [comment]
Here is what I have on my Windows 10 (1607) x64 with Node v9.0.0 :

```
yarn run v1.7.0
$ node index.js
issue : start
got tags :  SourceFile, errors, ExifToolVersion, FileName, Directory, FileSize, FileModifyDate, FileAccessDate, FileCreateDate, FilePermissions, FileType, FileTypeExtension, MIMEType, JFIFVersion, Comment, ExifByteOrder, Make, Model, Orientation, XResolution, YResolution, ResolutionUnit, Software, ModifyDate, YCbCrPositioning, ExposureTime, FNumber, ExposureProgram, ISO, ExifVersion, DateTimeOriginal, CreateDate, ComponentsConfiguration, ShutterSpeedValue, ApertureValue, BrightnessValue, ExposureCompensation, MaxApertureValue, MeteringMode, Flash, FocalLength, ColorSpace, ExifImageWidth, ExifImageHeight, ExposureMode, WhiteBalance, SceneCaptureType, Contrast, Saturation, Sharpness, GPSVersionID, GPSLatitudeRef, GPSLongitudeRef, GPSAltitudeRef, Padding, Compression, ThumbnailOffset, ThumbnailLength, ImageWidth, ImageHeight, EncodingProcess, BitsPerSample, ColorComponents, YCbCrSubSampling, Aperture, GPSAltitude, ImageSize, Megapixels, ShutterSpeed, ThumbnailImage, FocalLength35efl, LightValue
reading went good
writing a new date
Done in 2.32s.
```

**Comment by mceachen** [comment]
@Shuunen FWIW I've found that both `npm` and `yarn` won't actually update transitive dependencies correctly for existing `node_modules`. When I was trying different versions of exiftool-vendored, I had to `rm -rf yarn.lock node_modules ; yarn install` after I changed versions in my `package.json`.

**Comment by mceachen** [comment]
Also, just found out that the windows packaging of ExifTool can have issues: it installs a local perl into `~/AppData/Temp/par-####` and, most of the time it seems to work, but if you have concurrent first-time uses, they can corrupt that `par` directory. You'll see errors like 

`BatchCluster.onStartError() { error: 'stderr.data: IO error: Can\'t open file C:\\Users\\$USER\\AppData\\Local\\Temp\\par-6d726d\\cache-exiftool-10.95\\inc\\lib\\unicore\\lib\\Sc\\Hang.pl for write : Permission denied \r\n at -e line 631.' }`

I'm not sure how I feel about that--should exiftool-vendored look for those sorts of errors and try to recover (by shutting down all exiftools, `rm -rf` ing the par directory, and retrying all pending jobs?

**Comment by mceachen** [comment]
@Shuunen I've added your problematic image to the test suite. If https://travis-ci.org/mceachen/exiftool-vendored.js/builds/393226067 and https://ci.appveyor.com/project/mceachen/exiftool-vendored/build/0.1.290 pass, I can't repro your issue, and I'll have to close this.

**Comment by mceachen** [comment]
I cut a new release last night--your repair function is now available: https://github.com/mceachen/exiftool-vendored.js/blob/master/CHANGELOG.md#v510

Thanks for trying to reproduce the error. Feel free to fork and try to make the test I added fail--if we can get Appveyor to fail, then we can reopen this and I can repro. Until then, though, it seems like it works on my three windows images and Appveyor's 4 different node images, so I think we're good.

**Comment by Shuunen** [comment]
Thanks for your work and your lib :+1:  

You are on my thanks list on my photo archiver soft : https://github.com/Shuunen/photo-archiver <3
