### ISSUE TITLE
Original Image Width/Height return undefined

### ISSUE THREAD

**Issue by Cuneytt** [mceachen/exiftool-vendored.js#25]
Hi,

Thank you for this great tool.

Ran into this issue where running
```
exiftool ExifTool.jpg
```
gives 'Original Image Width/Height' to be 16. (ExifTool.jpg is a test image in the original exiftool distribution (Image-ExifTool-11.06.tar.gz) under  t/images directory)

When running through exiftool-vendored  getting 'undefined' for OriginalImageWidth/Height

**Comment by mceachen** [comment]
Thanks, I'll take a look now.

**Comment by mceachen** [comment]
I figured out what's happening. I added the `-fast` option for reading tags, based on the recommendation from Phil:

> The -fast option can significantly increase speed when extracting information from JPEG images which are piped across a slow network connection. However, with this option any information in a JPEG trailer is not extracted. For more substantial speed benefits, -fast2 may be used to also avoid extracting MakerNote information if this is not required.

If I remove the `-fast`, the `OriginalImageHeight` and `OriginalImageWidth` values are returned by ExifTool, but reading is slower (as the quote above states).

I'm going to add an enum option to the `read` function which defaults to current `-fast` behavior, but lets you choose between "slow" mode (neither -fast nor -fast2), "fast" mode (with -fast), or "fast2" mode (with -fast2). Sound good?

**Comment by Cuneytt** [comment]
Thank you @mceachen
