### ISSUE TITLE
Does't support -config option

### ISSUE THREAD

**Issue by denis-isaev** [mceachen/exiftool-vendored.js#27]
When I run
`exifTool.read(file,` ['-config /path/to/exiftool.config', '-n'])`
get the error message: "Invalid TAG name: config"

**Comment by mceachen** [comment]
`read` is running from within a `stay-open` stream, so I suspect giving a `-config` option there is too late.

If you use [exiftoolArgs](https://exiftool-vendored.js.org/interfaces/_exiftool_.exiftooloptions.html#exiftoolargs) (one of the new options in the ExifTool constructor), you should be able to add your option.

See http://owl.phy.queensu.ca/~phil/exiftool/exiftool_pod.html#config-CFGFILE for details.

**Comment by denis-isaev** [comment]
Thanks. This works:
`const exifTool = new ExifTool({ exiftoolArgs: ['-config', '/proj/ExifTool.config', '-stay_open', 'True', '-@', '-'] });`
`exifTool.read(file, ['-n'])`
