### ISSUE TITLE
What is the correct way to use exiftool-vendored with Parallelism

### ISSUE THREAD

**Issue by mesqueeb** [mceachen/exiftool-vendored.js#30]
#### The Question:

In the case of modifying 10,000+ photos: Do I have to manually create a throttling process to only process 1 photo with `exiftool.write` at the time and await each promise? Or does exiftool-vendored have auto queueing during `exiftool.write` on a large amount of photos?

#### The background & reason I can't use the Pearl CLI:

Since exiftool-vendored has `maxprocs` to help the CPU from being overloaded with Parallelism, I'm wondering how to correctly use exiftool-vendored.

[I have a complicated process](http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,9484.msg49090.html#msg49090) (where I need to look at about 500 folders in order, check the date of the first photo of the previous folder and apply changes depending on if this date is the same as the first photo of the next folder.)

_Also, since I am only a NodeJS and JavaScript developer I was hoping to use this library instead of the pearl CLI._

In my case I am planning to write a script that does these things synchronously:
1. do some date checking on relative sibling folders
2. make async modifications (with `exiftool.write`) to photos in the target folder (depending on the result of the checking in prev step)
3. await all these changes and go on to the next folder after

I don't anticipate a work overload since each folder doesn't have that many photos.

However, when there is a folder with a very large amount of photos to be modified in the above step 2, and my CPU is pushed to the max limit of the _exiftool-vendored_:
- will it automatically start queueing the async `exiftool.write` calls I made and wait until the CPU has regained some breathing space?
- **Or will I have to manually also create a throttling process to only process 1 photo with `exiftool.write` at the time** and await each modification?

**Comment by mceachen** [comment]
Thanks for asking on the forum.

Note that `maxprocs` limits the number of concurrent instances of ExifTool that will run at any given time. If you ask at a rate that is higher than that, your requests will be enqueued (and the promises will eventually resolve or reject). If you have enough RAM, and you've configured node to have enough heap, you might be able to enqueue 10,000 tasks without anything falling over. Did you try it? Make sure you have a backup (or two) of all your images, first!

Really, this is not an ExifTool-specific problem you're dealing with, this is just general concurrency. You should be able to find a lot of tutorials about handling concurrent tasks, as it's a general CS topic. Closing.
