### ISSUE TITLE
weird issue where exiftool stops processing without error

### ISSUE THREAD

**Issue by mesqueeb** [mceachen/exiftool-vendored.js#33]
I'm known to require a fairly complicated setup to organise my photo's, but I actually worked hard until I had a setup that's really straight forward and easy to reason about.

I just go through each folder synchronously and do each exiftool write also synchronously.
Meaning I `await` every single write.
Yet still my process gets cut off at around 30 folders (as seen in the screenshot below) but without any error!

Could you comment on my code how I should debug the `exiftool.write`, because I think I'm failing to log errors somewhere in the code.

First I wrapped `exiftool.write` into a `writeDate` function:
```js
const { ExifTool } = require('exiftool-vendored')
const exiftool = new ExifTool()

export default function (path, date) {
  return new Promise((resolve, reject) => {
    exiftool
      .write(path, {
        'MDItemFSCreationDate': date,
        'AllDates': date
      })
      .then(resolve).catch(reject)
  })
}
```
Then I do my process:
```js
const start = async () => {
  await asyncForEach(foldersByDate, async (date) => {
    console.log('=======', date, '========')
    const photoPaths = getFileList(ROOTPATH + '/' + date, true)
    await asyncForEach(photoPaths, async (photoPath) => {
      if (!photoPath.includes('.jpg')) return
      const photoName = photoPath.split('/').slice(-1)[0]
      const time = photoName.split(' ').slice(-1)[0].replace('.jpg', '').replace(/\./g, ':')
      await writeDate(photoPath, `${date}T${time}`).catch(console.error)
      // the catch.(console.error) should trigger on anything that goes wrong
    })
  })
  console.log('Finished!') // never reaches here
}
start()
```
Here down below you see the terminal console not showing any errors, but stopping mysteriously...

<img width="457" alt="image" src="https://user-images.githubusercontent.com/3253920/45273890-a9938180-b4ef-11e8-9e07-5761e490ee72.png">

Any advice is much appreciated, and I'm sorry to always come to you for help!!!!

(PS, the `asyncForEach` function is inspired from this [Medium post](https://codeburst.io/javascript-async-await-with-foreach-b6ba62bbf404) and works perfectly. The folders all have a few seconds in between them as they are logged in the console.)

**Comment by mceachen** [comment]
Your first step would be to enable logging. See https://github.com/mceachen/exiftool-vendored.js#logging-and-events. See the [tests](https://github.com/mceachen/exiftool-vendored.js/blob/master/src/_chai.spec.ts#L15) for an example.

In the future, please don't open issues to help debug your own code. If it's a bug in exiftool, especially if you can reproduce the issue, I'd be happy to look at it.

**Comment by mesqueeb** [comment]
@mceachen Thank you so much.
I will use your code to try and enable logging like so:
```js
setLogger(
  Logger.withLevels(
    Logger.withTimestamps(
      Logger.filterLevels(
        {
          trace: console.log,
          debug: console.log,
          info: console.log,
          warn: console.warn,
          error: console.error
        },
        (_p.env.LOG as any) || "error"
      )
    )
  )
)
```
However, when I further inspect this code it seems you import directly from:
```js
import { Logger, setLogger } from "./Logger"
```
I wonder when users of exiftool-vendored enable logging, from where they import `Logger` and `setLogger`.

If you have any advice on this i'd be willing to make a PR on the docs to add some clarification on this. But only if you feel this is helpful.
