### ISSUE TITLE
How to write \n (newline) to a tag value?

### ISSUE THREAD

**Issue by thomax** [mceachen/exiftool-vendored.js#37]
```
exiftool.write('path/to/image.jpg', {'Copyright': 'Agent Smith\n1999'})
```

Fails with a message that the file named "1999" doesn't exist (`Error: File not found - 1999`). How can I use newlines in a tag? Any help appreciated :)

**Comment by mceachen** [comment]
Thanks for the bug report!

TIL: ExifTool supports "[HTML entity escaping](http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,9669.msg50234.html#msg50234)". I've implemented this in version 7.4.0 which I just released.

**Comment by thomax** [comment]
Just to make sure it works in the CLI, I confirmed that the following works:

```bash
exiftool -E "-Copyright=going&#xa;going&#xa;gone" path/to/image.jpg
exiftool -Copyright path/to/image.jpg -b
going
going
gone%
```

(I've double-checked that I'm running exiftool-vendored@7.4.0)

**Comment by thomax** [comment]
I also tried this, without any more luck:
```js
exiftool.write('path/to/image.jpg', {'Copyright': 'going&#xa;going&#xa;gone'}, ['-E'])
```

**Comment by thomax** [comment]
Ah. I've read your source code, followed the callstack and I now understand what's going on.

With v7.4.0, the `-E` arg is passed by default and therefore all string characters which are HTML-entity-candidates will automatically be encoded. Thus, when I used the literal string `&#xa;` in my tag and the called `.write` it was encoded into `&#38;&#35;xa&#59;` internally and then back to `&#xa;` when exiftool (the cli command) took over.

The solution was simpler than I thought. Just use the string `\n` instead of `&#xa;` :)

**Comment by thomax** [comment]
I will now be quite. Thanks for the rubber duck session 👍
