### ISSUE TITLE
Upgrade to exiftool v11.21

### ISSUE THREAD

**Issue by Circuit8** [mceachen/exiftool-vendored.js#38]
Hey Matthew short request, any chance of a version bump to the latest version of exiftool v11.21? I would make a PR myself but taking a look at the .exe and perl versions of your library I had no idea about how to go about adding the new version of exiftool to that, a little bit above my paygrade.

All the best,
Josh

**Comment by mceachen** [comment]
No problem. Just pushed v7.5.0.

**Comment by Circuit8** [comment]
Awesome thanks!
