### ISSUE TITLE
Question about setting time with NPM exiftool.

### ISSUE THREAD

**Issue by mesqueeb** [mceachen/exiftool-vendored.js#4]
Dear @mceachen ,
Can I use your NPM exiftool directly from the terminal in macOS?
How would select a folder on my computer and set the taken datetime for all photos inside to e.g. 1990-01-30?

It would be great if I could see a sample!

(I know it's originally a perl program, but I thought to try yours, because I only know javascript. I'm not sure if I should run it through my browser or in the command line, and how to target files on my computer though!)

**Comment by mceachen** [comment]
This package (and the cross-platform dependency) provides:

1. A "vendored" (or self-hosted) copy of ExifTool for the current platform
2. Management of N copies of the ExifTool process, spawned in "keep alive" mode so they can run multiple commands (as perl can take some time to spinup)
3. Parsing of ExifTool results such that timestamps and locations are readily available to consumers

In your case, just use ExifTool directly. You can certainly ```npm install exiftool-vendored``` and ```cd node_modules/exiftool-vendored.pl``` (or ```.exe``` if you're on windows), and the binary will be right there, but you could also just install the thing from the actual website. The binary blobs should be identical for a given version.

https://www.google.com/search?q=exiftool+set+create+date is pretty rich with examples. 

See https://gist.github.com/mceachen/6068ab37cad7e13e8c74fa4d12f1c2ff#change-last-created-and-modified-for-files-in-a-directory
