### ISSUE TITLE
Error if IPTC ApplicationRecord Tags have a hyphen

### ISSUE THREAD

**Issue by Blatman** [mceachen/exiftool-vendored.js#40]
MacOS 10.13.6 High Sierra 

Reading IPTC tags from a .dng file and the hyphenated ones don't work 
Code fragment -

         var reado = 
        `Make: ${tags.Make},
         Model: ${tags.Model}, 
         Sub-location: ${tags.Sub-location},
         City: ${tags.City},
         Province-State: ${tags.Province-State},
         Country-PrimaryLocationName: ${tags.Country-PrimaryLocationName},
         UserComment: ${tags.UserComment}`;

        console.log('READO ', reado);
        })
        .catch(err => console.error("Something terrible happened: ", err))

eg: typical error is -
Something terrible happened: ReferenceError: State is not defined at exiftool.read.then (app.js:730) etc

Sub-location - FAIL
City - OK
Province-State - FAIL
Country-PrimaryLocationName - FAIL

Cheers,
Blane

**Comment by mceachen** [comment]
Could you please attach the DNG?

**Comment by mceachen** [comment]
Thanks, I'll look at it now.

**Comment by mceachen** [comment]
@Blatman you can't reference tags with dashes like that. 

Javascript interprets `tags.Province-State` as "the value of `tags.Province` minus the value of `State`," which explains your errors.

You want `tags["Province-State"]`.

**Comment by Blatman** [comment]
Ahhh - yes - too much brainfade at my end sorry for the waste of time

Cheers.
