### ISSUE TITLE
How to exclude or include specific tags while reading metadata

### ISSUE THREAD

**Issue by subbagudipalli** [mceachen/exiftool-vendored.js#44]
Here is code snippet to create an instance of exif tool. From this command, am expecting only format tag should be returned from the response. However, am getting all tags. 

var exiftool_vendored = require("exiftool-vendored") 
//const exifTool = new exiftool_vendored.ExifTool()
const exifTool = new exiftool_vendored.ExifTool({ exiftoolArgs: ["-stay_open", "True","-format","-@", "-"] });
console.log(exifTool.options)

However, am getting the response using Exiftool command:
Exiftool -stay_open True -format `INDD file path`
Response:
Format                          : application/x-indesign

I would like fetch only below metadata fields to avoid performance issues.  I have tried passing only "format" attribute but that didn't work. can you let me know how to exclude or include specific tags?

 var includeTags = ['*subject*',
                                'document_id',
                                'original_document_id',
                                'derived_from_document_id',
                                'derived_from_original_document_id',
                                'image*',
                                'format',
                                'thumbnail*',
                                'icc_profile_name',
                                'color*',
                                'file_size',
                                'file_type',
                                'creator*', 
                                'drm*',
                                'x_resolution',
                                'y_resolution',
                                'file_type_extension',
                                'file_name']

**Comment by mceachen** [comment]
Removing tag values from the result isn't a supported operation. 

The current args are simply added to the command, which includes [a lot of other required parameters](https://github.com/mceachen/exiftool-vendored.js/blob/master/src/ReadTask.ts#L58), including `-all`, which will override any attempt to remove prior tags. 

Removing a few tags from a JSON parse call will be inconsequential in overall performance compared to running the perl interpreter in an external process.

**Comment by subbagudipalli** [comment]
one suggestion, can you remove "-all" at the end by default in [ReadTask](https://github.com/mceachen/exiftool-vendored.js/blob/master/src/ReadTask.ts#L69)  rather it can be passed read method along with "-fast"(["-fast", "-all"])  in [ExifTool]( https://github.com/mceachen/exiftool-vendored.js/blob/master/src/ExifTool.ts#L242). Let me know if you have any concerns with this approach.

// Comment out below code in readTask
// TODO: Do you need -xmp:all, -all, or -all:all?
    //args.push("-all", "-charset", "filename=utf8", sourceFile)
 
// add -all option in read() method of exifTool
read(file: string, args: string[] = ["-fast", "-all"]): Promise<Tags> {
    return this.enqueueTask(() =>
      ReadTask.for(file, this.options.numericTags, args)
    )

**Comment by mceachen** [comment]
That will be a breaking change, so no.

Your use case is pretty specific. You should make a new ReadTask class (you should look at extending either ReadTask, [ExifToolTask](https://github.com/mceachen/exiftool-vendored.js/blob/master/src/ExifToolTask.ts), or even the base [Task](https://batch-cluster.js.org/classes/task.html) class), in your own codebase, make it do whatever you need it to do, and use the `[enqueueTask](https://github.com/mceachen/exiftool-vendored.js/blob/master/src/ExifTool.ts#L366)` method.

**Comment by mceachen** [comment]
@subbagudipalli I thought of a way to implement this and not break the API. See https://exiftool-vendored.js.org/classes/exiftool.html#readraw
