### ISSUE TITLE
read args parm bug or clarification needed 

### ISSUE THREAD

**Issue by rolanday** [mceachen/exiftool-vendored.js#45]
Great contribution. Thank you!

AFAICT, should be able to scope query to return tags listed in read args array as shown in following example: 
```
read('./image.jpg', ['-Model', '-Make', ...])
```
Is this unsupported, bug, or on me?

Thanks again,

-Roland.

**Comment by mceachen** [comment]
Hey @rolanday. Yeah, it's unsupported. Here's the discussion: https://github.com/mceachen/exiftool-vendored.js/issues/44

**Comment by mceachen** [comment]
OK, I thought of a way to do this and not break all the things. Please read the docs carefully before using! https://exiftool-vendored.js.org/classes/exiftool.html#readraw

**Comment by rolanday** [comment]
Thanks for the quick replies.

Above snippet was just to illustrate and definitely need a much fuller set of metadata. I'll take a look at your link (thank you!) but this isn't a deal breaker for me either way -- just about perf tuning and wanting to measure impact from reduced set of tags to read.

Thanks again!

-Roland.

**Comment by mceachen** [comment]
Please share any performance numbers (and if you can, the code and example images). If there's better performance we can wrestle out of this module, I'm all ears.

**Comment by rolanday** [comment]
I will do that. I'm quite pleased the perf relative to the perl implementation of app logic I'm porting to js so can leverage node / electron (about 2-3x faster), thanks to the parallelism and not reloading ExifTool. You did your homework!

Thanks again :-)
