### ISSUE TITLE
"Invalid unit tzoffsetMinutes" when using ExifDateTime.toDateTime()

### ISSUE THREAD

**Issue by weotch** [mceachen/exiftool-vendored.js#46]
I have a `CreateDate` that looks like this:
```
  CreateDate: 
   ExifDateTime {
     year: 2019,
     month: 3,
     day: 8,
     hour: 14,
     minute: 24,
     second: 54,
     millisecond: 0,
     tzoffsetMinutes: -480 }
```

When running `toDateTime()` on the `ExifDateTime` I am getting:

```
Error: Invalid unit tzoffsetMinutes
    at normalizeUnit (/Users/reinhard/Work/Open Source/dedupe-by-exif-date/node_modules/luxon/build/node/luxon.js:4954:26)
    at normalizeObject (/Users/reinhard/Work/Open Source/dedupe-by-exif-date/node_modules/luxon/build/node/luxon.js:264:18)
    at Function.fromObject (/Users/reinhard/Work/Open Source/dedupe-by-exif-date/node_modules/luxon/build/node/luxon.js:5273:24)
...
``` 

My goal was to convert the date to a timestamp via the `DateTime` instance.  Here's my yarn.lock for any versions of things you might want to know: http://yo.bkwld.com/09c026aa1698.

Thanks!

**Comment by mceachen** [comment]
Hey there, thanks for taking the time to open an issue.

Can you fill out the information in the bug report template, or, better, post a breaking test?

Thanks.

**Comment by mceachen** [comment]
I tried to repro this with 7613a69644f15eac983bf363fe02987f602065ec but the test passes.

Feel free to open if you can provide a failing test.

**Comment by mceachen** [comment]
:tada: I was able to repro your issue by updating to the latest luxon. I'll pin to the prior version for now.

**Comment by mceachen** [comment]
See https://github.com/moment/luxon/issues/469

**Comment by weotch** [comment]
Oh nice! 🍻
