### ISSUE TITLE
exiftool fs and child_process not found.

### ISSUE THREAD

**Issue by mesqueeb** [mceachen/exiftool-vendored.js#5]
I have installed laravel-mix to have a simple webpack wrapper.
I have added this script in `package.json`: ` "dev": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",`

When I try to run `npm run dev`, the only thing it should do is compile my JS file to include the top two lines of my js file:

````
let fs = require('fs');
import { exiftool } from "exiftool-vendored";
````

But I get the following error:
````
 Failed to compile with 3 errors

These dependencies were not found:

* fs in ./dev/run.js, ./~/exiftool-vendored/dist/exiftool_process.js
* child_process in ./~/exiftool-vendored/dist/exiftool_process.js

To install them, you can run: npm install --save fs child_process
````

**Comment by mceachen** [comment]
FWIW, `[child_process](https://nodejs.org/api/child_process.html#child_process_child_process)` and `[fs](https://nodejs.org/api/fs.html#fs_file_system)` are base node modules, so I don't see how they couldn't be available, unless you aren't in node, or you're using a custom loader.

It seems that [you got your problem solved](https://github.com/mceachen/exiftool-vendored.js/issues/6). Can you share your solution?

Thanks.

**Comment by mesqueeb** [comment]
@mceachen I solved it by using babel from the command line instead of running laravel mix. Maybe it's a bug in Laravel Mix?
