### ISSUE TITLE
Support writing metadata to existing files

### ISSUE THREAD

**Issue by mesqueeb** [mceachen/exiftool-vendored.js#6]
I was able to read the EXIF data successfully!
I am still a bit confused how to overwrite.

1. Could you add an example to the docs how to e.g. change the exif orientation of a file?
2. And if you have some spare time, a second example in the docs with the best/easiest way how to set a photo's date-taken to a different date, that would also be much appreciated.

Thank you very much!

This is what I have for the read part:
````
fs.readdir(dir, function (err, files) {
    files.forEach(function (file) {
    	exiftool
	    .read(dir+'/'+file)
	    .then((tags /*: Tags */) => {
            console.log(`【${file}】Orientation: ${tags.Orientation}`);
    });
});
````

**Comment by mceachen** [comment]
I have not implemented metadata writing.

If you want to have a swing at it, I'd be more than happy to review your PR!

**Comment by mceachen** [comment]
This is now supported in version 4.7.1.

**Comment by mesqueeb** [comment]
Wow this is GREAT NEWS!!!!
Now we can use NodeJS to fully read and write metadata of photos!
The world just became a better place!!!

**Comment by mesqueeb** [comment]
@mceachen 
I see that in the docs you've added this as example to write metadata:
`exiftool.write("path/to/file.jpg", { XPComment: "this is a test comment" });`

Can you also provide one example to edit the date taken of a picture?
Cheers!!

**Comment by mceachen** [comment]
I updated the docs and added tests, if you look at the latest diffs.

**Comment by borisimple** [comment]
> This is now supported in version 4.7.1.

What property should I use in order to specify that I want to overwrite the original files?
Can't find it anywhere in docs..

**Comment by mceachen** [comment]
> What property should I use in order to specify that I want to overwrite the original files? Can't find it anywhere in docs..

https://github.com/photostructure/exiftool-vendored.js/issues?q=is%3Aissue+overwrite_original

Specifically 

https://github.com/photostructure/exiftool-vendored.js/issues/64

I've also just added a reference to the .write method: https://photostructure.github.io/exiftool-vendored.js/classes/ExifTool.html#write

**Comment by borisimple** [comment]
> > What property should I use in order to specify that I want to overwrite the original files? Can't find it anywhere in docs..
> 
> https://github.com/photostructure/exiftool-vendored.js/issues?q=is%3Aissue+overwrite_original
> 
> Specifically
> 
> #64
> 
> I've also just added a reference to the .write method: https://photostructure.github.io/exiftool-vendored.js/classes/ExifTool.html#write

Awesome! I managed to use it in the write method instead of the constructor.
Thanks for the quick answer 👌🏻
