### ISSUE TITLE
Not fully compatible with yarn package manager

### ISSUE THREAD

**Issue by amokrushin** [mceachen/exiftool-vendored.js#7]
```bash
yarn add exiftool-vendored
node index.js
OK
```

```bash
yarn add anything-else
node index.js
Error: Cannot find module 'exiftool-vendored.pl'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/nodejs/test-exiftool/node_modules/exiftool-vendored/dist/ExifTool.js:17:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

`index.js` includes only import of `exiftool-vendored` module

Works ok only on clean install or if `exiftool-vendored.pl` explicitly added as a package dependency.

This does not cause much inconvenience in a case of `exiftool-vendored` is a direct dependency. But it is not so if there are intermediate dependencies.
For example `module-a -> module-b -> exiftool-vendored`. Whenever a `module-a` adds a new dependency, `mobule-b` will throw an error.

**Comment by mceachen** [comment]
This is a bug in yarn's interaction with [platform-dependent-modules](https://github.com/alykoshin/platform-dependent-modules). If you know of another way to have platform-specific dependencies, I'd appreciate any suggestions.

**Comment by amokrushin** [comment]
It's not a bug of yarn, it is a desired behaviour. `yarn add` command automatically removes all not explicitly defined modules.
You already has defined `os` section in `exiftool-vendored.exe` and `exiftool-vendored.pl` modules, so there is enough to remove `platform-dependent-modules` dependency and replace `package.json`'s `config` section with
```json
"optionalDependencies": {
    "exiftool-vendored.pl": "10.51.0",
    "exiftool-vendored.exe": "10.51.0"
}
```
Package manager (npm or yarn) will not install modules which aren't compatible with the current platform os. So on target platform only one of that modules will be installed.
But I don't know has this solution any side effect or not.

**Comment by mceachen** [comment]
I actually used this approach in versions prior to v1.5.3, (see https://github.com/mceachen/exiftool-vendored.js/commit/3690c73b2a10b0c6edfe419f6fc99a70ba2e5de2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

(This post)[https://stackoverflow.com/questions/15176082/npm-package-json-os-specific-dependency] highlights a defect with this approach: if the dependency fails to install, npm just reports it as a warning and carries on.

**Comment by amokrushin** [comment]
I don't understand what the problem was with thas solution.

It seems working as expected with both of yarn and npm:

```
am@135775:/srv/nodejs/qaa1nd07/base$ yarn
yarn install v0.24.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
warning qaa1nd07-dep-win32@0.1.1: The platform "linux" is incompatible with this module.
info "qaa1nd07-dep-win32@0.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.37s.
```

```bash
am@135775:/srv/nodejs/qaa1nd07/base$ npm i
qaa1nd07-base@0.1.0 /srv/nodejs/qaa1nd07/base
└── qaa1nd07-dep-linux@0.1.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: qaa1nd07-dep-win32@^0.1.1 (node_modules/qaa1nd07-dep-win32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for qaa1nd07-dep-win32@0.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN qaa1nd07-base@0.1.0 No description
npm WARN qaa1nd07-base@0.1.0 No repository field.
```

 If only problew was

> Making all versions of the dependency optional means that if your installation fails for a legitimate reason, it will silently skip installation and you will be missing a dependency you really need.

Then postinstall hook can verify that one was installed and throw error if not.

**Comment by mceachen** [comment]
NICE! I didn't even think about doing a validation step in the postinstall. Do you want to make a PR for this, or wait for me to do it?

Thanks!

**Comment by amokrushin** [comment]
PR is ready

**Comment by mceachen** [comment]
Thanks for your help. Travis now runs the builds with yarn, and I'll release this version tomorrow.
